server:
  port: 8085

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-service:9092}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.trusted.packages: "com.ecommerce.commondto.kafka"
        spring.json.use.type.headers: true


  mail:
    host: mailhog
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

notification:
  from-email: noreply@-e-commerce-shop.com
  confirmation-base-url: http://localhost:9091/
  confirmation-order-url: api/v1/orders/confirmation/

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
      registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

security:
  internal-api-key: ${SECURITY_INTERNAL_API_KEY}